schema = 3

[mod]
  [mod."github.com/Microsoft/go-winio"]
    version = "v0.5.0"
    hash = "sha256-5YO3JCbC4B6HLvL3gP4vZzN6IYNAYtf8i1hlVvwqd4g="
  [mod."github.com/VividCortex/ewma"]
    version = "v1.2.0"
    hash = "sha256-mHprIVRUOgs1qyYpiMO3bh6fCzDrqasDsaTaRE0oHXI="
  [mod."github.com/alecthomas/chroma"]
    version = "v0.10.0"
    hash = "sha256-p721vddVTv4iv1O0/dqpdk5xF6x9iLIHcrfh8JEVnqQ="
  [mod."github.com/atombender/go-jsonschema"]
    version = "v0.14.0"
    hash = "sha256-ESfOxfXzZboW2V/3c7sO923qX14W/cWTXu7O2Gk/piY="
  [mod."github.com/aymanbagabas/go-osc52"]
    version = "v1.0.3"
    hash = "sha256-+PPvxpq4eEcolG77a9g3r5Tw67Zs7hDOXS3nOYnizBQ="
  [mod."github.com/aymerick/douceur"]
    version = "v0.2.0"
    hash = "sha256-NiBX8EfOvLXNiK3pJaZX4N73YgfzdrzRXdiBFe3X3sE="
  [mod."github.com/charmbracelet/glamour"]
    version = "v0.6.0"
    hash = "sha256-L5V2P/9EPP80703KJUSMDiAPgjW1B4i1IbJADPmUCoY="
  [mod."github.com/cheggaaa/pb/v3"]
    version = "v3.0.8"
    hash = "sha256-SRqiaVWvZGAd296OgVYcpPkAERfnr7zRRX0X8HzPUsw="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.4.0"
    hash = "sha256-Pk/S2x2rX7xnGFLyoHEw09CoNQimvz/msdPRsxLaLsc="
  [mod."github.com/emirpasic/gods"]
    version = "v1.12.0"
    hash = "sha256-IavlXdTPaXr/n0ZjfPm3SmpndU70l5RnrINvqQ7GuEQ="
  [mod."github.com/fatih/color"]
    version = "v1.13.0"
    hash = "sha256-Xo0zFKLm/9NuChdHDhHoUFo8Oa7Mkb3ezZCu23SfOAk="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.4.9"
    hash = "sha256-HZBMhbFqcZM9oxSbWqISzEE7GF7JZpco5tyta6c4OcQ="
  [mod."github.com/go-git/gcfg"]
    version = "v1.5.0"
    hash = "sha256-A62eSLI/0y4sfwCsZhe/uoSC9Z3TryyW+PyWIcknYdE="
  [mod."github.com/go-git/go-billy/v5"]
    version = "v5.3.1"
    hash = "sha256-UdShPsStI2OBJig8Zv4Htyv5NiwKnYI41pwe4hIxv3Q="
  [mod."github.com/go-git/go-git/v5"]
    version = "v5.3.0"
    hash = "sha256-ThVdn4+S8hui9HMBmkc+zdZenvTqoPMjgimoDEcui4g="
  [mod."github.com/goccy/go-yaml"]
    version = "v1.11.2"
    hash = "sha256-l7YJw5aBoD6xxb6dK/CCcQ/9HhBOBjOm/QltCXtibkE="
  [mod."github.com/gorilla/css"]
    version = "v1.0.0"
    hash = "sha256-Mmt/IqHpgrtWpbr/AKcJyf/USQTqEuv1HVivY4eHzoQ="
  [mod."github.com/hashicorp/hcl"]
    version = "v1.0.0"
    hash = "sha256-xsRCmYyBfglMxeWUvTZqkaRLSW+V2FvNodEDjTGg1WA="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.12"
    hash = "sha256-IPGunEznxlUilS22LUU4p/QTA7f5+Goowf1Utg9ARpc="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jbenet/go-context"]
    version = "v0.0.0-20150711004518-d14ea06fba99"
    hash = "sha256-VANNCWNNpARH/ILQV9sCQsBWgyL2iFT+4AHZREpxIWE="
  [mod."github.com/kevinburke/ssh_config"]
    version = "v1.1.0"
    hash = "sha256-gs3Bak2D/ZKP1ZBQC53BNQtG/x6jiMwBVo+e161ZjLE="
  [mod."github.com/logrusorgru/aurora/v4"]
    version = "v4.0.0"
    hash = "sha256-PEH6+0YlK1zeqA7N4DDSkUk9BNBntphdUhwWqsElnCg="
  [mod."github.com/lucasb-eyer/go-colorful"]
    version = "v1.2.0"
    hash = "sha256-Gg9dDJFCTaHrKHRR1SrJgZ8fWieJkybljybkI9x0gyE="
  [mod."github.com/magiconair/properties"]
    version = "v1.8.5"
    hash = "sha256-dnVYJAEVGfVthpfcW3G1tsEZl8APaFgXXQ4MBqd9imw="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.12"
    hash = "sha256-Y1vCt0ShrCz4wSmwsppCfeLPLKrWusc2zM2lUFwDMyI="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.16"
    hash = "sha256-YMaPZvShDfA98vqw1+zWWl7M1IT4nHPGBrAt7kHo8Iw="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.14"
    hash = "sha256-O3QdxqAcJgQ+HL1v8oBA4iKBwJ2AlDN+F464027hWMU="
  [mod."github.com/mgutz/ansi"]
    version = "v0.0.0-20200706080929-d51e80ef957d"
    hash = "sha256-RY6deYqJKpTTttr5tH2VW+PtuUIcieEq3Y6fGqRL0vk="
  [mod."github.com/microcosm-cc/bluemonday"]
    version = "v1.0.21"
    hash = "sha256-kBzh0RKWgWPJteXgE5hm9I1YFMFGTDxGwNhjHKtnUSI="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/go-wordwrap"]
    version = "v1.0.1"
    hash = "sha256-fiD7kh5037BjA0vW6A2El0XArkK+4S5iTBjJB43BNYo="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.4.1"
    hash = "sha256-+xC5Th05FPFaWNMdAuX9YCwZpj0X1SD2t22a1VTkKNU="
  [mod."github.com/muesli/reflow"]
    version = "v0.3.0"
    hash = "sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc="
  [mod."github.com/muesli/termenv"]
    version = "v0.13.0"
    hash = "sha256-0KO2SSfj4J6Q3rXMohV+hnncUHiY7nAWU8hUbDQkLHA="
  [mod."github.com/nxadm/tail"]
    version = "v1.4.8"
    hash = "sha256-JP3RZVZLFhaBZ2VdF/fbyMPMLqrPZDjP98f1ey2OePo="
  [mod."github.com/olekukonko/tablewriter"]
    version = "v0.0.5"
    hash = "sha256-/5i70IkH/qSW5KjGzv8aQNKh9tHoz98tqtL0K2DMFn4="
  [mod."github.com/pelletier/go-toml"]
    version = "v1.9.1"
    hash = "sha256-IGTGeQpc8QlDIYcUYMi2C33a+oWgH7z1GM0w4WMWJTk="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/princjef/gomarkdoc"]
    version = "v1.1.0"
    hash = "sha256-LM5cBkKrPvCVWfWWG8nEUelFJRY1dYU2gEcxp8Fi2/k="
  [mod."github.com/princjef/mageutil"]
    version = "v1.0.0"
    hash = "sha256-eKhkJBx1fIF7dJfKdnLN6OgzehPDifzh29tcCXnIPoI="
  [mod."github.com/princjef/termdiff"]
    version = "v0.1.0"
    hash = "sha256-7hAg2Mi6FCXDnYSsulYhUNRaAwQiOKrVv9DlyJlLQ18="
  [mod."github.com/rivo/uniseg"]
    version = "v0.2.0"
    hash = "sha256-GLj0jiGrT03Ept4V6FXCN1yeZ/b6PpS3MEXK6rYQ8Eg="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/sanity-io/litter"]
    version = "v1.5.5"
    hash = "sha256-D1oP7mL4+sFaMU1S1WBmuwWYPMmr4ahi46SD4hPl/+0="
  [mod."github.com/sergi/go-diff"]
    version = "v1.3.1"
    hash = "sha256-XLA/BLIPuUU76yikXqIeRSXr7T7A3Uz6I27+mDxGj7w="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.8.1"
    hash = "sha256-vUIDlLXYBD74+JqdoSx+W3J6r5cOk63heo0ElsHizoM="
  [mod."github.com/spf13/afero"]
    version = "v1.6.0"
    hash = "sha256-ZzzshKZRvdo9JlPlhJ7VVymGfRSvP8XIY7fF2D24KHo="
  [mod."github.com/spf13/cast"]
    version = "v1.3.1"
    hash = "sha256-wT6IRl4ZFvzeyLlv7l/GJt39shnRRYHzxyDTh9AhaFE="
  [mod."github.com/spf13/cobra"]
    version = "v1.7.0"
    hash = "sha256-bom9Zpnz8XPwx9IVF+GAodd3NVQ1dM1Uwxn8sy4Gmzs="
  [mod."github.com/spf13/jwalterweatherman"]
    version = "v1.1.0"
    hash = "sha256-62BQtqTLF/eVrTOr7pUXE7AiHRjOVC8jQs3/Ehmflfs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spf13/viper"]
    version = "v1.7.1"
    hash = "sha256-AcR7S/bHMJftBqhQdrsjos71P6aNH2n5Z/AhiRlPka0="
  [mod."github.com/subosito/gotenv"]
    version = "v1.2.0"
    hash = "sha256-RUsfBl9xvHk8H6SPwiLi/BpHjkyO/YLvlFmRfGRIW1U="
  [mod."github.com/x-cray/logrus-prefixed-formatter"]
    version = "v0.5.2"
    hash = "sha256-yob8w9upAT+A279x0oek69tXM7E+6umNhIAv0GNsDFc="
  [mod."github.com/xanzy/ssh-agent"]
    version = "v0.3.0"
    hash = "sha256-vpgB8f9ryCcsUI3kVXEAqUNBwzu8oCLxu6QUyruQo14="
  [mod."github.com/yuin/goldmark"]
    version = "v1.5.2"
    hash = "sha256-IR19krj7bhVPsaIJrj6os5lT8/j/MilI5rqUSMGO+iU="
  [mod."github.com/yuin/goldmark-emoji"]
    version = "v1.0.1"
    hash = "sha256-liYCi6/EYG4obl51CzCaOmXf3fdzrU43J9VBZyHggEo="
  [mod."golang.org/x/crypto"]
    version = "v0.7.0"
    hash = "sha256-Yc4casCQyfOgIr48FV+NI9qhanhBuYnkph5iI7rDyZE="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20231006140011-7918f672742d"
    hash = "sha256-2SO1etTQ6UCUhADR5sgvDEDLHcj77pJKCIa/8mGDbAo="
  [mod."golang.org/x/net"]
    version = "v0.8.0"
    hash = "sha256-2cOtqa7aJ5mn64kZ+8+PVjJ4uGbhpXTpC1vm/+iaZzM="
  [mod."golang.org/x/sys"]
    version = "v0.13.0"
    hash = "sha256-/+RDZ0a0oEfJ0k304VqpJpdrl2ZXa3yFlOxy4mjW7w0="
  [mod."golang.org/x/term"]
    version = "v0.6.0"
    hash = "sha256-Ao0yXpwY8GyG+/23dVfJUYrfEfNUTES3RF45v1VhUAk="
  [mod."golang.org/x/text"]
    version = "v0.8.0"
    hash = "sha256-hgWFnT01DRmywBEXKYEVaOee7i6z8Ydz7zGbjcWwOgI="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20200804184101-5ec99f83aff1"
    hash = "sha256-62f++IO8Ia32CYy+xX8XDxCcT9r1sbPvVwoKV99gf7U="
  [mod."gopkg.in/ini.v1"]
    version = "v1.62.0"
    hash = "sha256-u9T6wgmbmG+hw8qiGLkWdxo9DgdrChFpuVpR53HzqbY="
  [mod."gopkg.in/warnings.v0"]
    version = "v0.1.2"
    hash = "sha256-ATVL9yEmgYbkJ1DkltDGRn/auGAjqGOfjQyBYyUo8s8="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."mvdan.cc/xurls/v2"]
    version = "v2.2.0"
    hash = "sha256-79mM1OaHydW5rlbOiA0jsGnMfvhuLKfr5kTgQp0P8XA="
