[[env]]
name = "GOROOT"
value = ""

[devshell]
name = "develpment-shell"
motd = """{106}Development Shell{reset}

Commands:
* lint: runs linter.
* generate: alias for go generate.
* test: runs test.

Use CTRL-D to leave the shell
"""

packages = [
    "go_1_21",
    "gotools",
    "go-tools",
    "golangci-lint",
]

startup.lint.text = "alias lint='golangci-lint run'"
startup.generate.text = "alias generate='go generate ./...'"
startup.test.text = "alias test='go test ./...'"
